apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: farfalla
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://__RDS_ENDPOINT__:5432/erp"
  SERVER_PORT: "8080"
