apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: farfalla
resources:
  - namespace.yaml
  - backend-config.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-servicemonitor.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - certificate.yaml
  - ingressroute.yaml
  - ../../platform/cert-manager
images:
  - name: __BACKEND_IMAGE__
    newName: __ECR_BACKEND_REPO__
    newTag: latest
  - name: __FRONTEND_IMAGE__
    newName: __ECR_FRONTEND_REPO__
    newTag: latest
